language: r

cache: packages

#r:
#  - oldrel
#  - release
#  - devel

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - gfortran-5

before_install:
  - mkdir -p ~/.R
  - VER=-5
  - echo "CC=gcc$(VER) -std=gnu99" >> ~/.R/Makevars
  - echo "CXX=g++$(VER)"           >> ~/.R/Makevars
  - echo 'CXX1X=$(CXX)'            >> ~/.R/Makevars
  - echo 'CXX11=$(CXX)'            >> ~/.R/Makevars
  - echo 'CXX14=$(CXX)'            >> ~/.R/Makevars
  - echo "SHLIB_CXXLD=g++$(VER)"   >> ~/.R/Makevars
  - echo "FC=gfortran$(VER)"       >> ~/.R/Makevars
  - echo "F77=gfortran$(VER)"      >> ~/.R/Makevars
