language: r

cache: packages

r:
 - oldrel
 - release
 - devel

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_install:
  - mkdir -p ~/.R
  - echo "CXX11 = g++-7 -fPIC" >> ~/.R/Makevars
  - echo "CXX14 = g++-7 -fPIC" >> ~/.R/Makevars
