// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _RcppXsimd_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// getProcessorSimdSupport
List getProcessorSimdSupport();
RcppExport SEXP _RcppXsimd_getProcessorSimdSupport() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(getProcessorSimdSupport());
    return rcpp_result_gen;
END_RCPP
}
// getSimdFeatures
List getSimdFeatures();
RcppExport SEXP _RcppXsimd_getSimdFeatures() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(getSimdFeatures());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppXsimd_rcpp_hello_world", (DL_FUNC) &_RcppXsimd_rcpp_hello_world, 0},
    {"_RcppXsimd_getProcessorSimdSupport", (DL_FUNC) &_RcppXsimd_getProcessorSimdSupport, 0},
    {"_RcppXsimd_getSimdFeatures", (DL_FUNC) &_RcppXsimd_getSimdFeatures, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppXsimd(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
