# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Poll OS and CPU for SIMD feature support
#' 
#' Execute CPUID to poll operating system and central processing unit for 
#' single instruction, multiple data feature support.
#' 
#' @return List of operating sytem (OS) and hardware (HW) feature support; 
#' see CPUID Wiki page for flag definitions
#' 
#' @references \url{https://en.wikipedia.org/wiki/CPUID}
#'
#' @export
getSimdFeatures <- function() {
    .Call(`_RcppXsimd_getSimdFeatures`)
}

